added working implementation of boundary conditions
sdd/kiddo_v1 pull request #21
Opened 2022-02-11 06:20 UTC by alvarozamora

(minimum viable product) with extensive testing suite; backwards compatible

2022-02-16 08:52 UTC, sdd commented
Great stuff @alvarozamora!  I'll have chance to review properly at the weekend - thanks so much for contributing!

2022-02-17 00:06 UTC, alvarozamora commented
I tried to come up with a way to enforce that a point is within the specified bounds, but I couldn't figure out a way that works without declaring any input point as mutable for the lifetime of the program since the iterator requires a reference to that mutated point.

2022-03-01 20:35 UTC, sdd requested changes
Apologies that it has taken a while to review this - it's been a busy couple of weekends for me. I think there are a few changes that are required, and I'd also like to have a play around with this branch in terms of running some profiling and seeing if it is possible to eliminate the Vecs that have been introduced. I can see a path, with a bit of work,  to bringing this in though. 

Thanks for your work so far.

2022-03-01 20:35 UTC, sdd commented on src/distance.rs
> +    let mut ds : Vec<T> = Vec::with_capacity(3_usize.pow(K as u32));
Is there a way we can do this with arrays instead of `Vec`s, since they are of a known size at compile time?

Performance is a key goal of this library, and eliminating heap allocations has been key to achieving this.

2022-03-01 20:35 UTC, sdd commented on src/distance.rs
> +    match K {
I would much prefer to have a solution that is able to remain generic across the number of dimensions, if at all possible - Let's have a think about if we can do that here

2022-03-01 20:35 UTC, sdd commented on src/kiddo.rs
>                  let iter = points.zip(bucket).map(|(p, d)| HeapElement {
I wonder if we might get slightly better performance by moving the conditional outside of the map. I'll test both ways.

```rust
let iter = if boxsize.is_none() {
    points.zip(bucket).map(|(p, d)| HeapElement {
        distance: distance(point, p),
        element: d
    })
} else {
    points.zip(bucket).map(|(p, d)| HeapElement {
        distance:  periodic_distance(point, p, boxsize, distance),
        element: d
    })
});
```

2022-03-01 20:35 UTC, sdd commented on src/kiddo.rs
> +pub fn periodic_distance<T: Float, const K: usize>(
This function is also defined in `src/distance.rs`, which seems like the right place for it, rather than here.

2022-03-01 20:35 UTC, sdd commented on src/distance.rs
> +pub fn periodic_distance<T: Float, const K: usize>(
I think this function should just be called `periodic`, as it is implicit from it being in the `distance.rs` file that it is a distance metric function and it saves useres from having to repeat the word "distance" when importing it, ie `use kiddo::distance::periodic` instead of `use kiddo::distance::periodic_distance`

2022-03-02 03:21 UTC, alvarozamora commented on src/distance.rs
> +    match K {
Despite being of length 3, this is independent of the number of dimensions because for every dimension you want the original data and two copies on the left and right edge of the domain.

2022-03-02 03:27 UTC, alvarozamora commented on src/distance.rs
> +    let mut ds : Vec<T> = Vec::with_capacity(3_usize.pow(K as u32));
The number of copies required cannot be known at compile time because the dimensionality is not necessarily known at compile time. Might not be the best solution, but the first thing that comes to mind is a rather verbose match operation like 

```rust
match K {
  1 => { ... // do 1-D case, which finds minimum of 3 distances },
  2 => { ... // do 2-D case, which finds minimum of 9 distances },
   ... 
  10 => { ... // do 10-D case, which finds minimum of 59,049 distances },
   _ => { ... // return error since the numbers are starting to get very large }
}
```

2022-03-02 03:30 UTC, alvarozamora commented on src/distance.rs
> +    let mut ds : Vec<T> = Vec::with_capacity(3_usize.pow(K as u32));
i'm just starting to learn Rust, so this may be wrong. It can be known at compile time if you have the user also specify `3.pow(K)` as a constant, and then perhaps assert that the const that should be equal to `3.pow(K)` is actually equal to `3.pow(K)`.

2022-03-02 03:31 UTC, alvarozamora commented on src/distance.rs
> +pub fn periodic_distance<T: Float, const K: usize>(
sounds great

2022-07-04 02:34 UTC, closed without merging