periodic boundary conditions mvp
sdd/kiddo_v1 pull request #32
Opened 2022-06-28 17:03 UTC by cavemanloverboy

By the way, this is @alvarozamora on another account. Here is an implementation which does everything with arrays.

2022-06-28 17:06 UTC, cavemanloverboy commented on src/kiddo.rs
> +impl<'a, 'b, A: Float + Zero + One + std::fmt::Debug, T: 'b, F: 'a, const K: usize> Iterator
Debug was added here for testing/debugging. We could remove it

2022-06-28 17:28 UTC, cavemanloverboy commented
As before, the two major changes when using periodic boundary conditions is in the check of all mirror images

```rust
,
    distance: &F,
    periodic: Option<[A; K]>,
) -> A
where
    A: 'a + 'b + Float,
    F: Fn(&[A; K], &[A; K]) -> A,
{
    // If not using periodic boundary conditions, just calculate and return distance
    if periodic.is_none() {

        return distance(a, b)


    // Otherwise, calculate the minimum distance from all mirror images
    } else {

        // Initialize min to max possible distance
        let mut min: A = periodic
            .unwrap()
            .iter()
            .fold(
                A::zero(),
                |acc, &x| acc + x*x,
            );

        // Calculate distance for every image
        for image_idx in 0..3_i32.pow(K as u32) {

            // Initialize current_image template
            let mut current_image: [i32; K] = [0; K];

            // Calculate current image
            for idx in 0..K {
                current_image[idx] = (( image_idx / 3_i32.pow(idx as u32)) % 3) - 1;
            }

            // Construct current image position
            let mut new_a: [A; K] = a.clone();
            for idx in 0..K {
                new_a[idx] = new_a[idx] + A::from(current_image[idx]).unwrap()*periodic.unwrap()[idx];
            }

            // Calculate distance for this image
            let image_distance = distance(&new_a, b);

            // Compare with current min
            min = min.min(image_distance);
        }

        min
    }
}
```

and that `distance_to_space` always returns 0, since you know beforehand what the space is and that it is everywhere.

2022-06-28 19:00 UTC, cavemanloverboy commented
I think I should move the tests of `get_distance` into the source as unit tests instead of having them as integration tests.

2022-06-28 20:19 UTC, cavemanloverboy commented
When using the periodic code, it appears I get a stack overflow when node capacity < pts added, so I think there's a bug in here.

2022-06-28 20:32 UTC, cavemanloverboy commented
I believe this is because I initialize the periodic kdtree with
```rust
            size: 0,
            min_bounds: [A::zero(); K],
            max_bounds: periodic,
```
 but still need
```rust
            size: 0,
            min_bounds: [A::infinity(); K],
            max_bounds: [A::neg_infinity(); K],
```

since this is for the bounds of the node, not the box. I will revert this change and instead add an error to `.add(...)` when the point is out of the box

2022-06-28 20:43 UTC, cavemanloverboy commented
I believe this is because I did
```rust
    pub fn periodic_with_per_node_capacity(capacity: usize, periodic: [A; K]) -> Result<Self, ErrorKind> {
        if capacity == 0 {
            return Err(ErrorKind::ZeroCapacity);
        }

        Ok(KdTree {
            size: 0,
            min_bounds: [A::zero(); K],
            max_bounds: periodic,
            content: Node::Leaf {
                points: Vec::with_capacity(capacity),
                bucket: Vec::with_capacity(capacity),
                capacity,
            },
            periodic: Some(periodic),
        })
    }
    ```
    but this still needs to have
    ```rust
                size: 0,
            min_bounds: [A::infinity(); K],
            max_bounds: [A::neg_infinity(); K],
            ```

2022-07-01 18:33 UTC, sdd commented
Thanks for your work on this, much appreciated! :-)  I'll review it over the weekend, and run some performance tests to see if it has any effect on the existing benchmarks 👍🏼

2022-07-01 21:57 UTC, cavemanloverboy commented
Awesome. There's a particular optimization that one can do for PBCs if you assume the distance metric is in the form of a p-norm, which requires a change to the crate. You can see what I do in my fork (which hard codes squared euclidean). With this optimization, the PBC impl only adds like 20-40% to query times. Build is basically exactly the same, so build time is unaffected. Without this optimization, you are looking at O(4-10)x longer query times.

2022-07-03 14:49 UTC, sdd requested changes
I'll run the benchmarks today, but here is some feedback on the code :-)

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +                    if self.periodic.is_some() {
`if-let` would make this a bit neater:

```rust
if let Some(periodic) = self.periodic {
    left = Box::new(KdTree::periodic_with_per_node_capacity(*capacity, periodic.clone()).unwrap());
    right = Box::new(KdTree::periodic_with_per_node_capacity(*capacity, periodic.clone()).unwrap());
} else {
    left = Box::new(KdTree::with_per_node_capacity(*capacity).unwrap());
    right = Box::new(KdTree::with_per_node_capacity(*capacity).unwrap());
}
```

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +        // Then check that point is in the bounds when periodic BCs are on
Similarly here:

```rust
 // Then check that point is in the bounds when periodic BCs are on
if let Some(periodic) = self.periodic {

    let (above_bound, below_bound) = periodic
// ...
```

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +            let (above_bound, below_bound) = periodic
Shouldn't this be `point.iter()` rather than `periodic.iter()`? You're comparing periodic to itself rather than to the point being checked

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +                .fold((false, false), |mut acc, &x| {
By using fold here, you end up continuing to check the remaining dimensions even if the first one fails the check. You can return early at the first failure instead. Something like this:


```rust
use itertools::izip;

if let Some((lower_bound, upper_bound)) = self.periodic {
    if izip!(point, lower_bound, upper_bound).any(|p, lower, upper| p < lower || p > upper) {
        return Err(ErrorKind::PeriodicOutOfBounds);
    }
}
Ok(())

```

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +    if periodic.is_none() {
Another place where `if-let` would be slightly neater :-)

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +            .unwrap()
using `if-let` as mentioned above will allow us to remove this `unwrap` too.

2022-07-03 14:49 UTC, sdd commented on src/kiddo.rs
> +                current_image[idx] = (( image_idx / 3_i32.pow(idx as u32)) % 3) - 1;
What is the significance of the number 3 here? Does this tie the implementation to only working on a tree with 3 dimensions? Or is it simply to iterate across (lower image, actual value, upper image) for each combination of dimensions? I'm unsure of this algo, sorry :-)

2022-07-03 15:40 UTC, cavemanloverboy commented on src/kiddo.rs
> +                current_image[idx] = (( image_idx / 3_i32.pow(idx as u32)) % 3) - 1;
It is for the mirror images. Technically with PBCs there are an infinite number of them but you only want to check neighboring ones. So, in 1D you check left and right regions. In 2D you check a square array of 9 regions. In 3D you check a cubic array of 27. 

This is where it can get slow but there is an optimization you can do when assuming the distance metric is a p-norm, which is to sum up `min(abs(a-b), abs(abs(a-b)-L)).powi(p)` for every component

2022-07-03 16:44 UTC, sdd commented
One more thing I've spotted. The build fails if you run `cargo build --all-features`. This is down to Serde not knowing how to serialize an `Option<[A; K]>`. We'll need another custom serializer function inside https://github.com/sdd/kiddo/blob/master/src/custom_serde.rs that we use for `KdTree.periodic`.

2022-07-03 16:51 UTC, cavemanloverboy commented
Sounds good. I will incorporate all of this feedback. I also want to do a few more tests to ensure everything works properly before we merge.

2022-07-03 22:28 UTC, cavemanloverboy commented
In incorporating this feedback and doing testing, I realized there is a much better way to implement this that is faster and cleaner. I first did it for another kNN impl this morning. I will update my impl for kiddo and push it here. Will hopefully be much cleaner and touch less of the code. Will also add more correctness tests.

2022-07-03 23:52 UTC, cavemanloverboy commented on src/kiddo.rs
> +                .fold((false, false), |mut acc, &x| {
yep..

2022-07-03 23:52 UTC, cavemanloverboy commented on src/kiddo.rs
> +            let (above_bound, below_bound) = periodic
yep..

2022-07-03 23:52 UTC, cavemanloverboy commented on src/kiddo.rs
> +                .fold((false, false), |mut acc, &x| {
will update this

2022-07-04 02:33 UTC, closed without merging